In [1]:
#!/usr/bin/env python
import snowflake.connector
import pandas as pd
import snowflake.connector
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine
# Credentials for connecting to snowflake. Migrate to properties file in the future.
USER = 'heinzlimetree'
ACCOUNT = 'um21928.us-east-1'
WAREHOUSE = 'COMPUTE_WH'
DATABASE = 'CAPSTONE'
SCHEMA = 'PUBLIC'
PASSWORD = 'Limetree123'

In [2]:
#creating a connection to snowflake to interact with the api
con = snowflake.connector.connect(
  user=USER,
  password=PASSWORD,
  account=ACCOUNT,
  warehouse=WAREHOUSE,
  database=DATABASE,
  schema=SCHEMA
)

In [3]:
#creating a connection to snowflake to interact with the api
engine = create_engine(URL(
    user=USER,
    password=PASSWORD,
    account=ACCOUNT,
    #warehouse=WAREHOUSE,
    database=DATABASE,
    schema=SCHEMA,
    warehouse = WAREHOUSE
))
 
connection = engine.connect()

In [4]:
sql_bank_open_close = """WITH bank AS(
    SELECT LEFT(ZIP_CD,5) as ZIP, LEFT(DT_EXIST_TERM,4) as branch_Close, LEFT(DT_OPEN,4) 
                        as branch_open, STATE_ABBR_NM as State FROM FFIEC_BRANCHES WHERE DOMESTIC_IND='Y'
)

SELECT a.year, a.STATE, a.ZIP, ifNull(num_open,0) as bank_open, 
       ifNull(num_close,0) as bank_close, (bank_open-bank_close) as bank_net, 
       (CASE WHEN bank_net > 0 THEN 1 WHEN bank_net = 0 THEN 0 ELSE -1 END) as GROUND_TRUTH 
FROM 
      
--Left Join base data
                    (SELECT year, zip, state from (select seq4() + 2004 as year
                                 from table(generator(rowcount => 15))
                                ) 
                     FULL OUTER JOIN bank
                     Group BY year, state, zip
                     ) AS a
                     
--Bank data
                     LEFT OUTER JOIN (
                       (SELECT ZIP,STATE,2004 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2004
                        Group BY ZIP,STATE)
                        UNION             
                        (SELECT ZIP,STATE,2005 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2005
                        Group BY ZIP,STATE)   
                        UNION             
                        (SELECT ZIP,STATE,2006 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2006
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2007 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2007
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2008 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2008                         
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2009 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2009
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2010 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2010
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2011 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2011
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2012 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2012
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2013 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2013
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2014 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2014
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2015 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2015
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2016 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2016
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2017 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2017
                        Group BY ZIP,STATE) 
                        UNION             
                        (SELECT ZIP,STATE,2018 as year_b, count(ZIP) as num_close
                        from bank 
                        where branch_Close = 2018
                        Group BY ZIP,STATE) 
                                     ) AS b
                     ON a.ZIP = b.ZIP and a.STATE = b.STATE and a.year = b.year_b

                     LEFT OUTER JOIN(
                         (SELECT ZIP, STATE, 2004 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2004
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2005 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2005
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2006 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2006
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2007 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2007
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2008 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2008
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2009 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2009
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2010 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2010
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2011 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2011
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2012 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2012
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2013 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2013
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2014 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2014
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2015 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2015
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2016 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2016
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2017 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2017
                         Group BY ZIP, STATE)
                         UNION
                         (SELECT ZIP, STATE, 2018 as year_c, count(ZIP) as num_open
                         from bank 
                         where branch_open = 2018
                         Group BY ZIP, STATE)
                                     ) AS c
                     ON a.ZIP = c.ZIP and a.STATE = c.STATE and a.year = c.year_c
                     

Where a.ZIP != 0 
ORDER BY a.YEAR, a.STATE, a.ZIP

"""

In [5]:
bank_open_close = pd.read_sql_query(sql_bank_open_close , engine)

In [6]:
bank_open_close

        year state    zip  bank_open  bank_close  bank_net  ground_truth
0       2004    AK  98733          0           0         0             0
1       2004    AK  99501          0           0         0             0
2       2004    AK  99502          0           0         0             0
3       2004    AK  99503          0           0         0             0
4       2004    AK  99504          0           0         0             0
5       2004    AK  99505          0           0         0             0
6       2004    AK  99506          0           0         0             0
7       2004    AK  99507          0           0         0             0
8       2004    AK  99508          0           0         0             0
9       2004    AK  99510          0           0         0             0
10      2004    AK  99513          0           0         0             0
11      2004    AK  99515          0           0         0             0
12      2004    AK  99519          0           0         0             0
13      2004    AK  99559          0           0         0             0
14      2004    AK  99574          0           0         0             0
15      2004    AK  99576          0           0         0             0
16      2004    AK  99577          0           0         0             0
17      2004    AK  99588          0           0         0             0
18      2004    AK  99603          0           0         0             0
19      2004    AK  99611          0           0         0             0
20      2004    AK  99613          0           0         0             0
21      2004    AK  99615          0           0         0             0
22      2004    AK  99645          0           0         0             0
23      2004    AK  99654          0           0         0             0
24      2004    AK  99661          0           0         0             0
25      2004    AK  99664          0           0         0             0
26      2004    AK  99669          1           0         1             1
27      2004    AK  99672          0           0         0             0
28      2004    AK  99685          0           0         0             0
29      2004    AK  99686          0           0         0             0
...      ...   ...    ...        ...         ...       ...           ...
340485  2018    WY  82609          1           0         1             1
340486  2018    WY  82633          0           0         0             0
340487  2018    WY  82636          0           1        -1            -1
340488  2018    WY  82637          0           0         0             0
340489  2018    WY  82644          0           0         0             0
340490  2018    WY  82649          0           0         0             0
340491  2018    WY  82701          0           0         0             0
340492  2018    WY  82716          0           0         0             0
340493  2018    WY  82718          0           0         0             0
340494  2018    WY  82721          0           0         0             0
340495  2018    WY  82730          0           0         0             0
340496  2018    WY  82732          0           0         0             0
340497  2018    WY  82801          0           0         0             0
340498  2018    WY  82834          0           0         0             0
340499  2018    WY  82901          0           1        -1            -1
340500  2018    WY  82930          0           0         0             0
340501  2018    WY  82935          0           0         0             0
340502  2018    WY  82937          0           0         0             0
340503  2018    WY  82939          0           0         0             0
340504  2018    WY  82941          0           0         0             0
340505  2018    WY  83001          0           0         0             0
340506  2018    WY  83002          0           0         0             0
340507  2018    WY  83014          0           0         0             0
340508  2018    WY  83025          0           0         0             0
340509  2018    WY  83101          0           0         0             0
340510  2018    WY  83110          0           0         0             0
340511  2018    WY  83113          0           0         0             0
340512  2018    WY  83118          0           0         0             0
340513  2018    WY  83127          0           0         0             0
340514  2018    WY  83128          0           0         0             0

[340515 rows x 7 columns]

In [7]:
sql_business_loan='''
SELECT zip, stalp as state, right(repdte,4) as year,
                                AVG(lnrenr4+lnrenr1+lnrenr2+lnrenr3+lnci4+lnci1+lnci2+lnci3+lnreag4+lnreag1+lnreag2+
                                 lnreag3+lnag4+lnag1+lnag2+lnag3+lnrenr4n+lnrenr1n+lnrenr2n+lnrenr3n+lnci4n+lnci1n+
                                 lnci2n+lnci3n+lnreag4n+lnreag1n+lnreag2n+lnreag3n+lnag4n+lnag1n+lnag2n+lnag3n) 
                                 as SMALL_BUSINESS_LOAN from SMALL_BUSINESS_LOAN where year <= 2018 Group BY year, state, zip
                                 ORDER BY year, state,zip
'''

In [8]:
bank_business_loan = pd.read_sql_query(sql_business_loan , engine)

In [9]:
bank_business_loan

         zip state  year  small_business_loan
0      99503    AK  2012         2.882960e+05
1      99510    AK  2012         5.798380e+05
2      99701    AK  2012         1.069350e+05
3      99801    AK  2012         6.531200e+04
4      99901    AK  2012         1.334700e+05
5      35020    AL  2012         4.844000e+04
6      35040    AL  2012         8.777200e+04
7      35045    AL  2012         3.780400e+04
8      35055    AL  2012         8.734000e+04
9      35094    AL  2012         5.012600e+04
10     35121    AL  2012         9.485800e+04
11     35125    AL  2012         4.888800e+04
12     35128    AL  2012         2.680480e+05
13     35150    AL  2012         4.442200e+04
14     35160    AL  2012         5.581400e+04
15     35203    AL  2012         7.730737e+06
16     35205    AL  2012         1.406400e+04
17     35209    AL  2012         4.871913e+05
18     35216    AL  2012         9.192000e+04
19     35233    AL  2012         6.229142e+06
20     35243    AL  2012         4.045300e+04
21     35401    AL  2012         1.403040e+05
22     35403    AL  2012         1.984000e+03
23     35406    AL  2012         3.019060e+05
24     35442    AL  2012         7.270200e+04
25     35462    AL  2012         2.385400e+04
26     35474    AL  2012         2.626600e+04
27     35481    AL  2012         2.267180e+05
28     35501    AL  2012         3.696867e+04
29     35555    AL  2012         6.313200e+04
...      ...   ...   ...                  ...
34742  26807    WV  2018         1.207580e+05
34743  26836    WV  2018         4.439320e+05
34744  26847    WV  2018         1.218200e+05
34745  26851    WV  2018         3.617200e+04
34746  82001    WY  2018         2.967200e+04
34747  82009    WY  2018         6.811600e+04
34748  82073    WY  2018         2.190000e+05
34749  82082    WY  2018         1.965800e+04
34750  82225    WY  2018         4.358600e+04
34751  82240    WY  2018         3.392650e+05
34752  82301    WY  2018         5.616000e+04
34753  82410    WY  2018         1.292300e+05
34754  82426    WY  2018         9.142600e+04
34755  82501    WY  2018         9.731000e+04
34756  82520    WY  2018         6.414800e+04
34757  82601    WY  2018         1.161500e+05
34758  82633    WY  2018         1.171840e+05
34759  82701    WY  2018         3.198800e+04
34760  82717    WY  2018         9.615200e+04
34761  82720    WY  2018         4.713200e+04
34762  82729    WY  2018         1.293820e+05
34763  82801    WY  2018         8.114000e+04
34764  82834    WY  2018         1.427270e+05
34765  82839    WY  2018         3.030000e+04
34766  82901    WY  2018         6.295200e+04
34767  82935    WY  2018         1.828600e+04
34768  82939    WY  2018         6.782800e+04
34769  83001    WY  2018         3.227800e+04
34770  83002    WY  2018         6.561600e+04
34771  83110    WY  2018         8.644600e+04

[34772 rows x 4 columns]

In [10]:
bank_business_loan['zip']=bank_business_loan['zip'].astype(int)
bank_business_loan['year']=bank_business_loan['year'].astype(int)

In [11]:
bank_open_close['zip']=bank_open_close['zip'].astype(int)
bank_open_close['year']=bank_open_close['year'].astype(int)

In [12]:
bank_open_close_loan = pd.merge(bank_open_close, bank_business_loan, on=['zip','state','year'], how='left')

In [13]:
bank_open_close_loan

,year,state,zip,bank_open,bank_close,bank_net,ground_truth,small_business_loan
0,2004,AK,98733,0,0,0,0,NaN
1,2004,AK,99501,0,0,0,0,NaN
2,2004,AK,99502,0,0,0,0,NaN
3,2004,AK,99503,0,0,0,0,NaN
4,2004,AK,99504,0,0,0,0,NaN
5,2004,AK,99505,0,0,0,0,NaN
6,2004,AK,99506,0,0,0,0,NaN
7,2004,AK,99507,0,0,0,0,NaN
8,2004,AK,99508,0,0,0,0,NaN
9,2004,AK,99510,0,0,0,0,NaN
10,2004,AK,99513,0,0,0,0,NaN
11,2004,AK,99515,0,0,0,0,NaN
12,2004,AK,99519,0,0,0,0,NaN
13,2004,AK,99559,0,0,0,0,NaN
14,2004,AK,99574,0,0,0,0,NaN
15,2004,AK,99576,0,0,0,0,NaN
16,2004,AK,99577,0,0,0,0,NaN
17,2004,AK,99588,0,0,0,0,NaN
18,2004,AK,99603,0,0,0,0,NaN
19,2004,AK,99611,0,0,0,0,NaN
20,2004,AK,99613,0,0,0,0,NaN
21,2004,AK,99615,0,0,0,0,NaN
22,2004,AK,99645,0,0,0,0,NaN
23,2004,AK,99654,0,0,0,0,NaN
24,2004,AK,99661,0,0,0,0,NaN
25,2004,AK,99664,0,0,0,0,NaN
26,2004,AK,99669,1,0,1,1,NaN
27,2004,AK,99672,0,0,0,0,NaN
28,2004,AK,99685,0,0,0,0,NaN
29,2004,AK,99686,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...
340485,2018,WY,82609,1,0,1,1,NaN
340486,2018,WY,82633,0,0,0,0,117184.0
340487,2018,WY,82636,0,1,-1,-1,NaN
340488,2018,WY,82637,0,0,0,0,NaN
340489,2018,WY,82644,0,0,0,0,NaN
340490,2018,WY,82649,0,0,0,0,NaN
340491,2018,WY,82701,0,0,0,0,31988.0
340492,2018,WY,82716,0,0,0,0,NaN
340493,2018,WY,82718,0,0,0,0,NaN
340494,2018,WY,82721,0,0,0,0,NaN
340495,2018,WY,82730,0,0,0,0,NaN
340496,2018,WY,82732,0,0,0,0,NaN
340497,2018,WY,82801,0,0,0,0,81140.0
340498,2018,WY,82834,0,0,0,0,142727.0
340499,2018,WY,82901,0,1,-1,-1,62952.0
340500,2018,WY,82930,0,0,0,0,NaN
340501,2018,WY,82935,0,0,0,0,18286.0
340502,2018,WY,82937,0,0,0,0,NaN
340503,2018,WY,82939,0,0,0,0,67828.0
340504,2018,WY,82941,0,0,0,0,NaN
340505,2018,WY,83001,0,0,0,0,32278.0
340506,2018,WY,83002,0,0,0,0,65616.0
340507,2018,WY,83014,0,0,0,0,NaN
340508,2018,WY,83025,0,0,0,0,NaN
340509,2018,WY,83101,0,0,0,0,NaN
340510,2018,WY,83110,0,0,0,0,86446.0
340511,2018,WY,83113,0,0,0,0,NaN
340512,2018,WY,83118,0,0,0,0,NaN
340513,2018,WY,83127,0,0,0,0,NaN
340514,2018,WY,83128,0,0,0,0,NaN

In [14]:
sql_bank_depo ='''
SELECT YEAR,STALPBR as state ,zip, sum(DEPSUMBR) as deposit
                                    from FDIC_DEPOSIT
                                    Group BY YEAR,state,ZIP
'''

In [15]:
bank_depo = pd.read_sql_query(sql_bank_depo , engine)

In [16]:
bank_depo

         year state      zip     deposit
0      2013.0    MI  43240.0  31978190.0
1      2013.0    FL  43240.0  18528035.0
2      2013.0    PA  18431.0   1529300.0
3      2013.0    OH  43212.0     47392.0
4      2013.0    KY  40361.0    606790.0
5      2013.0    SC  30308.0   1962398.0
6      2013.0    AL  31901.0   3473589.0
7      2013.0    GA  31076.0     32687.0
8      2013.0    MS  39074.0    715158.0
9      2013.0    IL  62501.0     70896.0
10     2013.0    CA  60675.0   1602103.0
11     2013.0    CO  60675.0    196400.0
12     2013.0    FL  75201.0    321295.0
13     2013.0    GA  31023.0    296644.0
14     2013.0    IL  62551.0     47783.0
15     2013.0    MI  48422.0    241819.0
16     2013.0    MI  75201.0  24827800.0
17     2013.0    MI  48858.0   2050761.0
18     2013.0    IL  62401.0   1690090.0
19     2013.0    IL  62056.0    391715.0
20     2013.0    MT  59101.0   3021510.0
21     2013.0    SD  59101.0    760126.0
22     2013.0    SD  57001.0     85487.0
23     2013.0    SD  57029.0    123537.0
24     2013.0    KS  66204.0    563076.0
25     2013.0    NE  68066.0    204926.0
26     2013.0    TX  71753.0     23692.0
27     2013.0    AR  72354.0     37359.0
28     2013.0    WI  54601.0    533824.0
29     2013.0    AR  72101.0     75707.0
...       ...   ...      ...         ...
80332  2016.0    OH  45030.0    187801.0
80333  2016.0    FL  70501.0   4132013.0
80334  2016.0    WA  98901.0   1353825.0
80335  2016.0    IL  60546.0    159640.0
80336  2016.0    NH   3867.0    176072.0
80337  2016.0    PA  18360.0   1181575.0
80338  2016.0    IL  57106.0   6060791.0
80339  2016.0    AR  63901.0    253409.0
80340  2016.0    CA  99362.0   1485761.0
80341  2016.0    NJ   7203.0    306210.0
80342  2016.0    IL  60641.0    343019.0
80343  2016.0    NJ  19040.0     58681.0
80344  2016.0    IN  46947.0    328414.0
80345  2016.0    WV  26034.0    269492.0
80346  2016.0    WA  98057.0    710826.0
80347  2016.0    WI  53220.0    351203.0
80348  2016.0    MA  10601.0    153723.0
80349  2016.0    IL  62439.0     34801.0
80350  2016.0    LA  70005.0     45072.0
80351  2016.0    IL  61354.0    124533.0
80352  2016.0    SC  29556.0     28315.0
80353  2016.0    NY  13027.0    115502.0
80354  2016.0    SC  29571.0     30404.0
80355  2016.0    ME   4901.0     60915.0
80356  2016.0    VA  24114.0     37106.0
80357  2016.0    OH  44820.0    205135.0
80358  2016.0    IN  47501.0     59651.0
80359  2016.0    NH   3820.0    248629.0
80360  2016.0    OR  98660.0     92098.0
80361  2016.0    MA   6604.0   3558729.0

[80362 rows x 4 columns]

In [17]:
bank_depo['zip']=bank_depo['zip'].astype(int)
bank_depo['year']=bank_depo['year'].astype(int)

In [18]:
bank_open_close_loan_depo = pd.merge(bank_open_close_loan, bank_depo, on=['zip','state','year'], how='left').fillna(0)

In [19]:
sql_race ='''
select year, "GEO.id2" as zip, HD01_VD01 as population, HD01_VD02
       as white_population, HD01_VD03  as Black_and_African_population, 
       HD01_VD04 as Indian_and_Alaska_population,  HD01_VD05 as Asian_population, HD01_VD06 as Islander_population,
       HD01_VD07 as other_race_population
       from B02001
'''

In [20]:
demo_race = pd.read_sql_query(sql_race , engine)

In [21]:
demo_race

,year,zip,population,white_population,black_and_african_population,indian_and_alaska_population,asian_population,islander_population,other_race_population
0,2011,4487,813,813,0,0,0,0,0
1,2011,4488,1249,1230,0,8,3,0,0
2,2011,4489,207,207,0,0,0,0,0
3,2011,4490,264,256,0,2,0,0,0
4,2011,4491,129,129,0,0,0,0,0
5,2011,4492,136,130,0,6,0,0,0
6,2011,4493,1877,1805,0,38,0,0,0
7,2011,4495,389,387,0,2,0,0,0
8,2011,4496,3761,3701,4,15,2,0,0
9,2011,4497,396,384,0,4,0,0,0
10,2011,4530,11028,10504,243,22,83,0,64
11,2011,4535,576,565,7,4,0,0,0
12,2011,4537,2020,2020,0,0,0,0,0
13,2011,4538,2147,2125,6,0,16,0,0
14,2011,4539,1255,1202,20,33,0,0,0
15,2011,4541,62,62,0,0,0,0,0
16,2011,4543,2241,2188,0,17,36,0,0
17,2011,4544,700,700,0,0,0,0,0
18,2011,4547,1135,1131,0,0,0,0,0
19,2011,4548,826,819,0,1,6,0,0
20,2011,4551,824,794,4,5,0,0,0
21,2011,4553,1728,1690,6,0,19,0,6
22,2011,4554,645,597,0,0,0,0,0
23,2011,4555,1551,1504,5,0,0,0,0
24,2011,4556,1088,1012,21,1,16,0,2
25,2011,4558,291,291,0,0,0,0,0
26,2011,4562,2392,2359,26,0,3,0,0
27,2011,4563,1291,1285,0,0,1,0,5
28,2011,4564,510,510,0,0,0,0,0
29,2011,4568,528,528,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
430517,2017,89448,1371,1332,0,0,12,0,12
430518,2017,89449,3284,2600,49,45,42,13,370
430519,2017,89450,91,91,0,0,0,0,0
430520,2017,89451,8795,7618,19,105,150,6,727
430521,2017,89460,13347,11470,21,672,271,107,492
430522,2017,89501,3852,2934,247,135,122,103,150
430523,2017,89502,45953,34149,1048,1027,2558,325,5506
430524,2017,89503,28620,23300,703,239,1896,269,995
430525,2017,89506,41279,32027,1440,433,1783,170,3164
430526,2017,89508,12418,10875,120,136,278,13,163
430527,2017,89509,34717,29565,586,180,1494,273,1417
430528,2017,89510,1545,1263,11,207,6,23,3
430529,2017,89511,25498,22954,155,198,874,92,379
430530,2017,89512,25815,17086,1227,463,1749,510,3067
430531,2017,89519,8250,7433,79,42,378,10,31
430532,2017,89521,29675,24649,393,212,2438,180,395
430533,2017,89523,35266,27806,645,594,3129,130,1440
430534,2017,89701,26440,20643,552,805,451,52,2711
430535,2017,89702,0,0,0,0,0,0,0
430536,2017,89703,9789,8500,134,293,502,26,179
430537,2017,89704,3822,3583,32,16,94,0,14
430538,2017,89705,5253,4485,25,103,60,0,382
430539,2017,89706,19482,15939,245,267,404,0,2289
430540,2017,89801,25920,21824,364,1297,365,18,1269
430541,2017,89815,14027,13188,5,376,140,9,218
430542,2017,89820,5561,4924,3,422,3,29,120
430543,2017,89821,488,465,0,23,0,0,0
430544,2017,89822,2371,2209,47,94,3,0,13
430545,2017,89823,147,141,0,6,0,0,0
430546,2017,89825,1561,1561,0,0,0,0,0

In [22]:
bank_vs_demo_race = pd.merge(bank_open_close_loan_depo, demo_race, on=['zip','year'], how='left').fillna(0)

In [23]:
bank_vs_demo_race

,year,state,zip,bank_open,bank_close,bank_net,ground_truth,small_business_loan,deposit,population,white_population,black_and_african_population,indian_and_alaska_population,asian_population,islander_population,other_race_population
0,2004,AK,98733,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2004,AK,99501,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2004,AK,99502,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2004,AK,99503,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2004,AK,99504,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2004,AK,99505,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2004,AK,99506,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2004,AK,99507,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2004,AK,99508,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2004,AK,99510,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2004,AK,99513,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2004,AK,99515,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2004,AK,99519,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2004,AK,99559,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2004,AK,99574,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2004,AK,99576,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2004,AK,99577,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2004,AK,99588,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2004,AK,99603,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2004,AK,99611,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2004,AK,99613,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2004,AK,99615,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2004,AK,99645,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2004,AK,99654,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2004,AK,99661,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2004,AK,99664,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2004,AK,99669,1,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2004,AK,99672,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2004,AK,99685,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2004,AK,99686,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465501,2018,WY,82609,1,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465502,2018,WY,82633,0,0,0,0,117184.0,511854.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465503,2018,WY,82636,0,1,-1,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465504,2018,WY,82637,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465505,2018,WY,82644,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465506,2018,WY,82649,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465507,2018,WY,82701,0,0,0,0,31988.0,116663.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465508,2018,WY,82716,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465509,2018,WY,82718,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465510,2018,WY,82721,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465511,2018,WY,82730,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465512,2018,WY,82732,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465513,2018,WY,82801,0,0,0,0,81140.0,256701.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465514,2018,WY,82834,0,0,0,0,142727.0,375234.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465515,2018,WY,82901,0,1,-1,-1,62952.0,310461.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465516,2018,WY,82930,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465517,2018,WY,82935,0,0,0,0,18286.0,27729.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465518,2018,WY,82937,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465519,2018,WY,82939,0,0,0,0,67828.0,177597.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465520,2018,WY,82941,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465521,2018,WY,83001,0,0,0,0,32278.0,258366.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465522,2018,WY,83002,0,0,0,0,65616.0,687229.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465523,2018,WY,83014,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465524,2018,WY,83025,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465525,2018,WY,83101,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465526,2018,WY,83110,0,0,0,0,86446.0,175633.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465527,2018,WY,83113,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465528,2018,WY,83118,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465529,2018,WY,83127,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465530,2018,WY,83128,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
# business loan data is from 2012 to 2018
# deposit is from 2008 to 2019
# bank open/close is from 2004 to 2018

bank_vs_demo_race

,year,state,zip,bank_open,bank_close,bank_net,ground_truth,small_business_loan,deposit,population,white_population,black_and_african_population,indian_and_alaska_population,asian_population,islander_population,other_race_population
0,2004,AK,98733,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2004,AK,99501,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2004,AK,99502,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2004,AK,99503,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2004,AK,99504,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2004,AK,99505,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2004,AK,99506,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2004,AK,99507,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2004,AK,99508,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2004,AK,99510,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2004,AK,99513,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2004,AK,99515,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2004,AK,99519,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2004,AK,99559,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2004,AK,99574,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2004,AK,99576,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2004,AK,99577,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2004,AK,99588,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2004,AK,99603,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2004,AK,99611,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2004,AK,99613,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2004,AK,99615,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2004,AK,99645,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2004,AK,99654,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2004,AK,99661,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2004,AK,99664,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2004,AK,99669,1,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2004,AK,99672,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2004,AK,99685,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2004,AK,99686,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465501,2018,WY,82609,1,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465502,2018,WY,82633,0,0,0,0,117184.0,511854.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465503,2018,WY,82636,0,1,-1,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465504,2018,WY,82637,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465505,2018,WY,82644,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465506,2018,WY,82649,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465507,2018,WY,82701,0,0,0,0,31988.0,116663.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465508,2018,WY,82716,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465509,2018,WY,82718,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465510,2018,WY,82721,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465511,2018,WY,82730,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465512,2018,WY,82732,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465513,2018,WY,82801,0,0,0,0,81140.0,256701.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465514,2018,WY,82834,0,0,0,0,142727.0,375234.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465515,2018,WY,82901,0,1,-1,-1,62952.0,310461.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465516,2018,WY,82930,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465517,2018,WY,82935,0,0,0,0,18286.0,27729.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465518,2018,WY,82937,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465519,2018,WY,82939,0,0,0,0,67828.0,177597.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465520,2018,WY,82941,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465521,2018,WY,83001,0,0,0,0,32278.0,258366.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465522,2018,WY,83002,0,0,0,0,65616.0,687229.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465523,2018,WY,83014,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465524,2018,WY,83025,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465525,2018,WY,83101,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465526,2018,WY,83110,0,0,0,0,86446.0,175633.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465527,2018,WY,83113,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465528,2018,WY,83118,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465529,2018,WY,83127,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465530,2018,WY,83128,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
sql_age_population ='''
select year, "geo.id2" as zip, HC01_EST_VC01 as population, 
       (CASE WHEN HC02_EST_VC28 = '-' THEN 0 ELSE HC02_EST_VC28 END) as age_18_over_percent,
       (CASE WHEN HC01_EST_VC29 = '-' THEN 0 ELSE HC01_EST_VC29 END) as age_60_over_percent,
       population *(100-age_18_over_percent)/100 as population_0_to_17,  
       population *(age_18_over_percent-age_60_over_percent)/100 as population_18_to_59,
       population *(age_60_over_percent/100)  as poplulation_over_60
from ACS_AGE_POPULATION
'''

In [26]:
demo_age_population = pd.read_sql_query(sql_age_population , engine)

In [27]:
bank_vs_demo_race_age = pd.merge(bank_vs_demo_race, demo_age_population, on=['zip','year'], how='left').fillna(0)

In [28]:
bank_vs_demo_race_age

,year,state,zip,bank_open,bank_close,bank_net,ground_truth,small_business_loan,deposit,population_x,...,indian_and_alaska_population,asian_population,islander_population,other_race_population,population_y,age_18_over_percent,age_60_over_percent,population_0_to_17,population_18_to_59,poplulation_over_60
0,2004,AK,98733,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2004,AK,99501,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2004,AK,99502,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2004,AK,99503,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2004,AK,99504,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2004,AK,99505,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2004,AK,99506,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2004,AK,99507,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2004,AK,99508,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2004,AK,99510,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2004,AK,99513,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2004,AK,99515,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2004,AK,99519,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2004,AK,99559,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2004,AK,99574,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2004,AK,99576,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2004,AK,99577,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2004,AK,99588,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2004,AK,99603,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2004,AK,99611,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2004,AK,99613,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2004,AK,99615,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2004,AK,99645,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2004,AK,99654,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2004,AK,99661,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2004,AK,99664,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2004,AK,99669,1,0,1,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2004,AK,99672,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2004,AK,99685,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2004,AK,99686,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465501,2018,WY,82609,1,0,1,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465502,2018,WY,82633,0,0,0,0,117184.0,511854.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465503,2018,WY,82636,0,1,-1,-1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465504,2018,WY,82637,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465505,2018,WY,82644,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465506,2018,WY,82649,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465507,2018,WY,82701,0,0,0,0,31988.0,116663.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465508,2018,WY,82716,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465509,2018,WY,82718,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465510,2018,WY,82721,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465511,2018,WY,82730,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465512,2018,WY,82732,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465513,2018,WY,82801,0,0,0,0,81140.0,256701.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465514,2018,WY,82834,0,0,0,0,142727.0,375234.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465515,2018,WY,82901,0,1,-1,-1,62952.0,310461.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465516,2018,WY,82930,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465517,2018,WY,82935,0,0,0,0,18286.0,27729.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465518,2018,WY,82937,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465519,2018,WY,82939,0,0,0,0,67828.0,177597.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465520,2018,WY,82941,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465521,2018,WY,83001,0,0,0,0,32278.0,258366.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465522,2018,WY,83002,0,0,0,0,65616.0,687229.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465523,2018,WY,83014,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465524,2018,WY,83025,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465525,2018,WY,83101,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465526,2018,WY,83110,0,0,0,0,86446.0,175633.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465527,2018,WY,83113,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465528,2018,WY,83118,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465529,2018,WY,83127,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465530,2018,WY,83128,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
sql_unemployment_rate = '''
select year,"geo.id2" as zip, 
       (CASE WHEN HC03_VC05 = '-' THEN 0 ELSE (100-HC03_VC05) END) as unemployment_rate
from ACS_UNEMPLOYMENT_RATE
'''

In [30]:
demo_unemployment_rate = pd.read_sql_query(sql_unemployment_rate , engine)

In [31]:
bank_vs_demo = pd.merge(bank_vs_demo_race_age, demo_unemployment_rate, on=['zip','year'], how='left').fillna(0)

In [35]:
bank_vs_demo

,index,year,state,zip,bank_open,bank_close,bank_net,ground_truth,small_business_loan,deposit,...,asian_population,islander_population,other_race_population,population_y,age_18_over_percent,age_60_over_percent,population_0_to_17,population_18_to_59,poplulation_over_60,unemployment_rate
0,26,2004,AK,99669,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,37,2004,AK,99709,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,62,2004,AL,35007,2,2,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,64,2004,AL,35016,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,93,2004,AL,35080,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,98,2004,AL,35097,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,104,2004,AL,35124,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,106,2004,AL,35126,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,109,2004,AL,35131,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,111,2004,AL,35146,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,119,2004,AL,35179,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,125,2004,AL,35203,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,131,2004,AL,35209,2,0,2,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,138,2004,AL,35216,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,141,2004,AL,35223,2,0,2,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,143,2004,AL,35233,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,149,2004,AL,35244,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,154,2004,AL,35405,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,155,2004,AL,35406,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,165,2004,AL,35476,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,198,2004,AL,35601,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,199,2004,AL,35603,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,208,2004,AL,35630,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,235,2004,AL,35758,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,237,2004,AL,35760,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,245,2004,AL,35801,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,250,2004,AL,35806,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,280,2004,AL,35983,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,283,2004,AL,35987,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,287,2004,AL,36010,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313903,465447,2018,WV,26651,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313904,465452,2018,WV,26719,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313905,465456,2018,WV,26757,0,0,0,0,66473.0,360613.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313906,465461,2018,WV,26807,0,0,0,0,120758.0,208187.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313907,465464,2018,WV,26836,0,0,0,0,443932.0,1223883.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313908,465465,2018,WV,26847,0,0,0,0,121820.0,216245.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313909,465466,2018,WY,82001,0,0,0,0,29672.0,101072.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313910,465470,2018,WY,82009,0,0,0,0,68116.0,164974.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313911,465474,2018,WY,82073,0,0,0,0,219000.0,184033.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313912,465475,2018,WY,82082,0,0,0,0,19658.0,26602.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313913,465480,2018,WY,82225,0,0,0,0,43586.0,46484.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313914,465481,2018,WY,82240,0,0,0,0,339265.0,1012764.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313915,465482,2018,WY,82301,0,0,0,0,56160.0,248480.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313916,465487,2018,WY,82414,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313917,465488,2018,WY,82426,0,0,0,0,91426.0,205933.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313918,465494,2018,WY,82501,0,0,0,0,97310.0,124280.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313919,465497,2018,WY,82520,0,0,0,0,64148.0,133024.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313920,465498,2018,WY,82601,0,0,0,0,116150.0,887306.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313921,465501,2018,WY,82609,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313922,465502,2018,WY,82633,0,0,0,0,117184.0,511854.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313923,465503,2018,WY,82636,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313924,465507,2018,WY,82701,0,0,0,0,31988.0,116663.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313925,465513,2018,WY,82801,0,0,0,0,81140.0,256701.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313926,465514,2018,WY,82834,0,0,0,0,142727.0,375234.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313927,465515,2018,WY,82901,0,1,-1,-1,62952.0,310461.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313928,465517,2018,WY,82935,0,0,0,0,18286.0,27729.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313929,465519,2018,WY,82939,0,0,0,0,67828.0,177597.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313930,465521,2018,WY,83001,0,0,0,0,32278.0,258366.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313931,465522,2018,WY,83002,0,0,0,0,65616.0,687229.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313932,465526,2018,WY,83110,0,0,0,0,86446.0,175633.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
# delete all 0 rows except year/state/zip because we cannot use to train the model
condition = (bank_vs_demo[['bank_open','bank_close','bank_net','ground_truth','small_business_loan','deposit','indian_and_alaska_population'
                                       ,'population_y']].sum(axis=1) == 0.0)
bank_vs_demo = bank_vs_demo.drop(bank_vs_demo[condition].index).reset_index()

In [33]:
# business loan data is from 2012 to 2018
# deposit is from 2008 to 2019
# bank open/close is from 2004 to 2018
# race is from 2011 to 2017
# unemployment is from 2011 to 2017
# age population is from 2011 to 2016

bank_vs_demo

,index,year,state,zip,bank_open,bank_close,bank_net,ground_truth,small_business_loan,deposit,...,asian_population,islander_population,other_race_population,population_y,age_18_over_percent,age_60_over_percent,population_0_to_17,population_18_to_59,poplulation_over_60,unemployment_rate
0,26,2004,AK,99669,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,37,2004,AK,99709,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,62,2004,AL,35007,2,2,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,64,2004,AL,35016,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,93,2004,AL,35080,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,98,2004,AL,35097,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,104,2004,AL,35124,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,106,2004,AL,35126,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,109,2004,AL,35131,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,111,2004,AL,35146,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,119,2004,AL,35179,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,125,2004,AL,35203,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,131,2004,AL,35209,2,0,2,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,138,2004,AL,35216,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,141,2004,AL,35223,2,0,2,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,143,2004,AL,35233,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,149,2004,AL,35244,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,154,2004,AL,35405,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,155,2004,AL,35406,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,165,2004,AL,35476,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,198,2004,AL,35601,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,199,2004,AL,35603,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,208,2004,AL,35630,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,235,2004,AL,35758,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,237,2004,AL,35760,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,245,2004,AL,35801,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,250,2004,AL,35806,1,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,280,2004,AL,35983,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,283,2004,AL,35987,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,287,2004,AL,36010,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313903,465447,2018,WV,26651,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313904,465452,2018,WV,26719,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313905,465456,2018,WV,26757,0,0,0,0,66473.0,360613.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313906,465461,2018,WV,26807,0,0,0,0,120758.0,208187.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313907,465464,2018,WV,26836,0,0,0,0,443932.0,1223883.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313908,465465,2018,WV,26847,0,0,0,0,121820.0,216245.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313909,465466,2018,WY,82001,0,0,0,0,29672.0,101072.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313910,465470,2018,WY,82009,0,0,0,0,68116.0,164974.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313911,465474,2018,WY,82073,0,0,0,0,219000.0,184033.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313912,465475,2018,WY,82082,0,0,0,0,19658.0,26602.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313913,465480,2018,WY,82225,0,0,0,0,43586.0,46484.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313914,465481,2018,WY,82240,0,0,0,0,339265.0,1012764.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313915,465482,2018,WY,82301,0,0,0,0,56160.0,248480.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313916,465487,2018,WY,82414,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313917,465488,2018,WY,82426,0,0,0,0,91426.0,205933.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313918,465494,2018,WY,82501,0,0,0,0,97310.0,124280.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313919,465497,2018,WY,82520,0,0,0,0,64148.0,133024.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313920,465498,2018,WY,82601,0,0,0,0,116150.0,887306.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313921,465501,2018,WY,82609,1,0,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313922,465502,2018,WY,82633,0,0,0,0,117184.0,511854.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313923,465503,2018,WY,82636,0,1,-1,-1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313924,465507,2018,WY,82701,0,0,0,0,31988.0,116663.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313925,465513,2018,WY,82801,0,0,0,0,81140.0,256701.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313926,465514,2018,WY,82834,0,0,0,0,142727.0,375234.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313927,465515,2018,WY,82901,0,1,-1,-1,62952.0,310461.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313928,465517,2018,WY,82935,0,0,0,0,18286.0,27729.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313929,465519,2018,WY,82939,0,0,0,0,67828.0,177597.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313930,465521,2018,WY,83001,0,0,0,0,32278.0,258366.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313931,465522,2018,WY,83002,0,0,0,0,65616.0,687229.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313932,465526,2018,WY,83110,0,0,0,0,86446.0,175633.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Write data set to a csv file
dataset_directory = "D:\\Coursework\\Capstone\\clean_repo\\data_load\\dataset"
bank_vs_demo.to_csv(directory+"\\bank_vs_demo_data")

In [36]:
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# [model creation]
# 
 
from sklearn.datasets import load_iris
from sklearn import tree
import csv

# drop year, state, zip
bank_vs_demo = bank_vs_demo.drop(['index','year','state','zip','bank_open','bank_close',
                                                            'bank_net'], axis=1)
data_list = bank_vs_demo.drop('ground_truth', axis=1)
label_list = bank_vs_demo['ground_truth']

In [37]:
from sklearn.model_selection import train_test_split

#Create train and test data. test_size 0.3 means 30% of data will be test data.
#change dataframe to matrix - data_list and label-list
train_data, test_data, train_label, test_label = train_test_split(data_list.as_matrix(), label_list.as_matrix(), test_size=0.3, random_state=None )

C:\Users\kenns\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """

In [38]:
#option1 decision tree classifier model
clf = tree.DecisionTreeClassifier(max_depth = 3)
clf = clf.fit(train_data, train_label)

# create prediction
predicted = clf.predict(test_data)

# print out predict and correct label
print('=============== predicted ===============')
print(predicted)
print('============== correct_ans (label) ==============')
print(test_label)
print('=============== accuracy =================')
print(sum(predicted == test_label) / len(test_label))

=============== predicted ===============
[0 0 0 ... 0 0 0]
============== correct_ans (label) ==============
[0 0 0 ... 0 0 0]
=============== accuracy =================
0.8334253557018475

In [ ]:
#option2 support vector machine

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix 
import matplotlib.pyplot as plt
import seaborn as sns

model_svc = SVC(kernel='linear', random_state=None)
model_svc.fit(train_data, train_label)

# create predict label
pred_test = model_svc.predict(test_data)

# create confusion matrix
results = confusion_matrix(test_label, pred_test)

# print the accuracy score on the test data
print('Accuracy Score :',accuracy_score(test_label, pred_test) )

# create label
labels = ['Open','Constant','Close']

In [ ]:
# display the heatmap of confusion matrix on the test data
fig, ax = plt.subplots(figsize=(10, 5)) 
ax.set_title('Confusion Matrix - Test Data')
sns.heatmap(results, annot =True, fmt="d", xticklabels=labels, yticklabels=labels)

plt.xlabel('Predicted Labels')
plt.ylabel('Groundtruth')

plt.show()